services:
  app:
    build: .
    tty: true
    develop:
      watch:
        - action: sync+restart
          path: src/
          target: /app/src
        - action: rebuild
          path: package.json
    ports:
      - 3000:3000
    command: yarn dev
